IGNF/geopf-extensions-openlayers

- package.json
- src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
- src/packages/Controls/LayerSwitcher/LayerSwitcher.js
- src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
closes https://github.com/IGNF/geoportal-extensions-openlayers/issues/123
> feat(layer-switcher): use dsfr slider for opacity

- package.json
- src/packages/CSS/Controls/LocationSelector/DSFRlocationStyle.css
- src/packages/CSS/DSFRgeneralWidget.css
fixes https://github.com/IGNF/geoportal-extensions-openlayers/issues/131
> fix(widgets): croix invisible

- package.json
- src/packages/CSS/Controls/SearchEngine/DSFRsearchEngineStyle.css
- src/packages/CSS/Controls/SearchEngine/GPFsearchEngine.css
- src/packages/CSS/Controls/SearchEngine/GPFsearchEngineStyle.css
> fix(search:css): reduction des marges en centrage

- package.json
- src/packages/CSS/Controls/SearchEngine/DSFRsearchEngineStyle.css
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/145
> fix(search): disparition recherche avancé en mobile + améliorations diverses (centrage)

- package.json
- src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
- src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
> fix(ls)(dsfr): darkmode dragndrop btn

- package.json
- src/packages/CSS/Controls/Isochron/DSFRisochronStyle.css
- src/packages/CSS/Controls/Isochron/GPFisochron.css
- src/packages/CSS/Controls/Isochron/GPFisochronStyle.css
- src/packages/CSS/Controls/LocationSelector/DSFRlocationStyle.css
- src/packages/CSS/Controls/Route/DSFRrouteStyle.css
- src/packages/CSS/Controls/Route/GPFroute.css
- src/packages/CSS/Controls/Route/GPFrouteStyle.css
- src/packages/CSS/DSFRgeneralWidget.css
- src/packages/Controls/Isocurve/Isocurve.js
- src/packages/Controls/Isocurve/IsocurveDOM.js
- src/packages/Controls/LocationSelector/LocationSelectorDOM.js
- src/packages/Controls/Route/Route.js
- src/packages/Controls/Route/RouteDOM.js
https://github.com/IGNF/geopf-extensions-openlayers/issues/150
TODO: Prioritaire : mieux gérer la hauteur max de la fenêtre avec les collisions @lowzonenose 
TODO: améliorer le rendu pour le style non-dsfr des extensions (peu prioritaire)
> feat(iti)(iso)(dsfr): améltioration et harmonisation du rendu. maquette.

- package.json
- src/packages/CSS/Controls/Legends/DSFRlegendsStyle.css
cf https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/290#issuecomment-2301897320
Pour la "avoir un redimensionnement adaptatif", attente de la gestion des collisions @lowzonenose
> fix(legend): increase max height of legend

- package.json
- src/packages/CSS/DSFRgeneralWidget.css
- src/packages/CSS/GPFgeneralWidget.css
- src/packages/Controls/OverviewMap/GeoportalOverviewMap.js
https://github.com/IGNF/geopf-extensions-openlayers/pull/153#issuecomment-2305223875
Fix de ce truc là
> fix(css): caret affiché en navigation tab

- package.json
- src/packages/CSS/Controls/ElevationPath/DSFRelevationPathStyle.css
- src/packages/CSS/Controls/ElevationPath/GPFelevationPath.css
- src/packages/CSS/Controls/ElevationPath/GPFelevationPathStyle.css
- src/packages/Controls/ElevationPath/ElevationPath.js
- src/packages/Controls/ElevationPath/ElevationPathDOM.js
- src/packages/Controls/ElevationPath/ProfileElevationPathDOM.js
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/15#issuecomment-2304682701
S'approche du DSFR au maximum pour permettre d'avancer sur la maquette.
> feat(elevationPath): compatible dsfr

- package.json
- src/packages/CSS/DSFRgeneralWidget.css
- src/packages/Controls/OverviewMap/GeoportalOverviewMap.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/175
tester que ça ne casse pas l'affichage sur tous les autres boutons avec cet indicateur
> fix(overview)(dsfr): css when aria pressed

- src/packages/CSS/Controls/Territories/DSFRterritoriesStyle.css
- src/packages/Controls/Territories/Territories.js
Territory Responsive en plein écran + fermeture du panel quand choix d'un territoire
> Fix(Territory): le widget est responsive

- package.json
- src/packages/Controls/MousePosition/MousePosition.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/181
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/183
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/323
> fix(mousePosition): liste déroulante draggable true

- package.json
- samples-src/pages/tests/Default/pages-ol-modules-dsrf-default.html
- src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
- src/packages/CSS/Controls/Territories/DSFRterritoriesStyle.css
- src/packages/CSS/DSFRgeneralWidget.css
- src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
- src/packages/Controls/Territories/TerritoriesDOM.js
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/222
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/223
> fix(ls)(dsfr)(mobile): fullscreen et généralisation du comportement

- package.json
- src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/191
> fix(ls): le panneau informations des couches reste affiché même quand la couche est supprimée

- package.json
- src/packages/Controls/OverviewMap/GeoportalOverviewMap.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/203
fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/346
> fix(overview): wrong btn status if no collapse option

- package.json
- src/packages/Controls/LayerImport/LayerImportDOM.js
- src/packages/Controls/ReverseGeocode/ReverseGeocodeDOM.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/202
> fix(import/reverse): bouton validation secondary

- package.json
- samples-src/pages/tests/Drawing/pages-ol-drawing-modules-dsfr-default.html
- samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-default.html
- src/packages/Services/Search.js
https://github.com/IGNF/geopf-extensions-openlayers/issues/213
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/355
> feat(search): wmts layers priority

- package.json
- src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
- src/packages/CSS/DSFRgeneralWidget.css
- src/packages/Controls/Catalog/CatalogDOM.js
- src/packages/Controls/Drawing/DrawingDOM.js
- src/packages/Controls/ElevationPath/ElevationPathDOM.js
- src/packages/Controls/FullScreen/GeoportalFullScreen.js
- src/packages/Controls/GetFeatureInfo/GetFeatureInfoDOM.js
- src/packages/Controls/Isocurve/IsocurveDOM.js
- src/packages/Controls/LayerImport/LayerImportDOM.js
- src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
- src/packages/Controls/Legends/LegendsDOM.js
- src/packages/Controls/Measures/MeasureAreaDOM.js
- src/packages/Controls/Measures/MeasureAzimuthDOM.js
- src/packages/Controls/Measures/MeasureLengthDOM.js
- src/packages/Controls/MousePosition/MousePositionDOM.js
- src/packages/Controls/ReverseGeocode/ReverseGeocodeDOM.js
- src/packages/Controls/Route/RouteDOM.js
- src/packages/Controls/Territories/TerritoriesDOM.js
- src/packages/Controls/Zoom/GeoportalZoom.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/218
Je me suis inspiré du génie de @elias75015 ici https://github.com/IGNF/geopf-extensions-openlayers/pull/107/files
Les modification faites dans cette PR (ajout de span dans les btns) nous permet de ne plus avoir besoin du code d'elias fait dans https://github.com/IGNF/geopf-extensions-openlayers/pull/107/files
> fix(chrome): boutons activés

- src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
https://github.com/IGNF/geopf-extensions-openlayers/issues/221
Bug fix du ticket si dessus
> fix(GFI): Exception sur un import KML ou GPX

- package.json
- src/packages/CSS/Controls/Zoom/GPFzoom.css
- src/packages/CSS/Controls/Zoom/GPFzoomStyle.css
- src/packages/Controls/Zoom/GeoportalZoom.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/223
> style(zoom:classic): changer style des boutons zoom + et -

- package.json
- src/packages/CSS/DSFRgeneralWidget.css
- src/packages/Controls/Catalog/CatalogDOM.js
- src/packages/Controls/Drawing/DrawingDOM.js
- src/packages/Controls/ElevationPath/ElevationPathDOM.js
- src/packages/Controls/FullScreen/GeoportalFullScreen.js
- src/packages/Controls/GetFeatureInfo/GetFeatureInfoDOM.js
- src/packages/Controls/Isocurve/IsocurveDOM.js
- src/packages/Controls/LayerImport/LayerImportDOM.js
- src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
- src/packages/Controls/Legends/LegendsDOM.js
- src/packages/Controls/Measures/MeasureAreaDOM.js
- src/packages/Controls/Measures/MeasureAzimuthDOM.js
- src/packages/Controls/Measures/MeasureLengthDOM.js
- src/packages/Controls/MousePosition/MousePositionDOM.js
- src/packages/Controls/OverviewMap/GeoportalOverviewMap.js
- src/packages/Controls/ReverseGeocode/ReverseGeocodeDOM.js
- src/packages/Controls/Route/RouteDOM.js
- src/packages/Controls/SearchEngine/SearchEngineDOM.js
- src/packages/Controls/Territories/TerritoriesDOM.js
- src/packages/Controls/Zoom/GeoportalZoom.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/239
\+ orthographe référencée ici https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/362#issuecomment-2456971263
> fix(accessibility): retirer les alt des boutons widgets

- package.json
- src/packages/Utils/PanelManager.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/259
> fix(fullscreen): ouverture de widgets quitte le plein ecran

- package.json
- src/packages/Controls/ElevationPath/ElevationPath.js
> fix(elevation-path): rendu super pourri si ça boucle

- package.json
- src/packages/CSS/Controls/SearchEngine/DSFRsearchEngineStyle.css
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/285
> fix(dsfr)(advanced-search): le Panneau ne s'affiche pas correctement

- samples-src/pages/tests/Default/pages-ol-bundle-data-url.html
- samples-src/resources/data/configuration/sample.json
- src/packages/Utils/AutoLoadConfig.js
- src/packages/bundle.js
Issue  #287 
```html
<script src="{{ baseurl }}/dist/bundle/GpfExtOL.js" data-url="{{ resources }}/data/configuration/sample.json"></script>
<script type="text/javascript">
window.onload = function () { ... }
</script>
```
> Fix: Utilisation de l'attribut data-url pour charger la configuration

- package.json
- src/packages/Controls/Drawing/Drawing.js
fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/pull/373#issuecomment-2511721025
> fix(dawing)(dsfr): icon disparait en fermant et réouvrant

- snippets/widgets/Controls/WidgetEntries/widget.js
- src/packages/Controls/Catalog/Catalog.js
- src/packages/Controls/ControlList/ControlList.js
- src/packages/Controls/Drawing/Drawing.js
- src/packages/Controls/Export/Export.js
- src/packages/Controls/FullScreen/GeoportalFullScreen.js
- src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
- src/packages/Controls/Isocurve/Isocurve.js
- src/packages/Controls/LayerImport/LayerImport.js
- src/packages/Controls/Legends/Legends.js
- src/packages/Controls/LocationSelector/LocationSelector.js
- src/packages/Controls/MousePosition/MousePosition.js
- src/packages/Controls/OverviewMap/GeoportalOverviewMap.js
- src/packages/Controls/ReverseGeocode/ReverseGeocode.js
- src/packages/Controls/Route/Route.js
- src/packages/Controls/SearchEngine/SearchEngine.js
- src/packages/Controls/Territories/Territories.js
variable importante pour créer le menu des widgets avec les icons côté entrée carto
> ajout CLASSNAME pour tous les widgets

- package.json
- src/packages/Controls/ReverseGeocode/ReverseGeocode.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/255
> feat(reverse): limite les zones dessinnées par rapport aux limites du service

- package.json
- src/packages/CSS/Controls/SearchEngine/DSFRsearchEngineStyle.css
- src/packages/CSS/Controls/SearchEngine/GPFsearchEngine.css
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/307
> fix(search): position des résultats quand le search est dans un coin

- src/packages/Layers/SourceWFS.js
> Ajout import geoportal-access-lib sur SourceWFS

- COMPILE.md
- CONTRIBUTING.md
- CONTRIBUTORS.md
Ajout d'un fichier CONTRIBUTING.md pour définir les régles et workflows de contribution
Mise à jour du fichier CONTRIBUTORS.md
Ajout d'un fichier COMPILE.md pour détailler les commandes permettant de builder, tester, publier le projet
> chore(doc): ajout de la documentation de contribution et compilation

- package.json
- src/packages/Controls/Drawing/Drawing.js
fix du bug de drawing sur entree carto
> fix: drawing interaction (ol.Overlay)

- DRAFT_CHANGELOG.md
- package.json
- src/packages/CSS/DSFRgeneralWidget.css
- src/packages/Controls/ContextMenu/ContextMenuDOM.js
amaury le bien né est l'intelligence derrière cette PR
> css fix adresse et coord

- src/packages/Controls/ContextMenu/ContextMenu.js
- src/packages/Controls/ContextMenu/ContextMenuDOM.js
- src/packages/Controls/Route/Route.js
Correction des bugs ci dessous : 
fix https://github.com/IGNF/geopf-extensions-openlayers/issues/336
fix https://github.com/IGNF/geopf-extensions-openlayers/issues/337
fix https://github.com/IGNF/geopf-extensions-openlayers/issues/338
fix https://github.com/IGNF/geopf-extensions-openlayers/issues/339
> fix(contextmenu): bugs

- DRAFT_CHANGELOG.md
- package.json
- src/packages/CSS/Controls/Route/DSFRrouteStyle.css
- src/packages/CSS/Controls/Route/GPFrouteStyle.css
- src/packages/Controls/Route/Route.js
- src/packages/Controls/Route/RouteDOM.js
Problème dans l'affichage des noms d'étape (départ, étape, arrivée)
Problème dans l'affichage des valeurs d'étape si coordonnées
Problème de mise à jour des valeurs entre deux calculs si coordonnées
Problème de lisibilité
**Avant**
**Après**
**Avant**
**Après**
> style(route): panel de résultats plus lisible

- package.json
- samples-src/pages/tests/LayerSwitcher/pages-ol-layerswitcher-modules-default.html
- samples-src/pages/tests/LayerSwitcher/pages-ol-layerswitcher-modules-dsfr-default.html
- src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css
- src/packages/CSS/Controls/LayerSwitcher/GPFlayerSwitcher.css
- src/packages/Controls/LayerSwitcher/LayerSwitcher.js
- src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
see https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/99#issuecomment-2830858687
see https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/206
a tester sur pages-ol-layerswitcher-modules-dsfr-default.html
Pour l'instant, non conforme à la maquette : attente de la refonte css complète.
> feat(layer-switcher): vector tile style select

- package.json
- src/packages/Controls/SearchEngine/SearchEngine.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/374
> feat(position): center the marker when clicked

- DRAFT_CHANGELOG.md
- package.json
- src/packages/Controls/LayerSwitcher/LayerSwitcher.js
> fix(ls): greyscale vectortiles after style switch

- DRAFT_CHANGELOG.md
- package.json
- src/packages/CSS/Controls/Zoom/DSFRzoomStyle.css
- src/packages/CSS/DSFRgeneralWidget.css
- src/packages/Controls/Catalog/Catalog.js
- src/packages/Utils/LayerConfigUtils.js
cf https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/615
> ui(buttons): new style

- DRAFT_CHANGELOG.md
- src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
Correction https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/677
Avant : 
Après :
> fix(layerswitcher): display none edit en mode mobile si pas dispo
