src/packages/CSS/Controls/SearchEngine/DSFRsearchEngineStyle.css, src/packages/CSS/Controls/SearchEngine/GPFsearchEngine.css, src/packages/CSS/Controls/SearchEngine/GPFsearchEngineStyle.css, src/packages/Controls/SearchEngine/SearchEngineDOM.js
Avant :
Les éléments du haut et du bas sont un peu décalés.
Après : 
Les éléments du haut et du bas sont un mieux alignés et centrés, avec une réduction des marges et de la largeur globale du wiget.
=> fix(search:css): meilleur centrage des éléments de la barre de recherche en DSFR

package.json, src/packages/Controls/Isocurve/Isocurve.js, src/packages/Controls/Route/Route.js
Dû au fait que this._initContainer(map) est appelé à chaque setMap().
Correctif : ne rien faire dans ce _initContainer si le container est déjà initialisé (plus que 0 nœuds enfants)
Pour tester, dans samples-src/pages/tests/Isocurve/pages-ol-isocurve-modules-dsfr-default.html et samples-src/pages/tests/Route/pages-ol-route-modules-default.html, ajouter après le map.addControl(route ou iso) :
> map.removeControl(route ou iso);
> map.addControl(route ou iso);
> map.removeControl(route ou iso);
> map.addControl(route ou iso);
> map.removeControl(route ou iso);
> map.addControl(route ou iso);
Avant / après la PR
=> fix(route)(isochrone): container initialized multiple times if add + remove + add control

package.json, samples-src/pages/tests/Isocurve/pages-ol-isocurve-modules-default.html, samples-src/pages/tests/Isocurve/pages-ol-isocurve-modules-dsfr-default.html, samples-src/pages/tests/Route/pages-ol-route-modules-default.html, samples-src/pages/tests/Route/pages-ol-route-modules-dsfr-default.html, src/packages/CSS/Controls/Isochron/DSFRisochronStyle.css, src/packages/CSS/Controls/Isochron/GPFisochron.css, src/packages/CSS/Controls/Route/DSFRrouteStyle.css, src/packages/CSS/Controls/Route/GPFroute.css
Fixe une hauteur max pour les formulaires itinéraire et isochrone à 400px, avec ajout d'une scrollbar, afin que le panel ne dépasse pas de la fenêtre carto (si celle-ci n'est pas trop petite...)
Avant PR : 
Le formulaire dépasse et impossible de l'utiliser car pas de possibilité de défilement
Après PR : 
Possibilité de défiler le formulaire avec une scrollbar
=> fix(panel:iso/route): ajout d'une hauteur max avec scrollbar en DSFR

package.json, src/packages/CSS/Controls/LayerSwitcher/DSFRlayerSwitcherStyle.css, src/packages/CSS/Controls/LayerSwitcher/GPFlayerSwitcher.css, src/packages/CSS/Controls/LayerSwitcher/GPFlayerSwitcherStyle.css, src/packages/Controls/Control.js, src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/87
Checker le bon fonctionnement des widgets avec plusieurs modales (search, layerimport, layerswitcher).
A priori pas de nouveau bug : layerimport ne marche pas sur la main pour l'ouverture de la fenêtre mapbox ou wmts cf https://github.com/IGNF/geopf-extensions-openlayers/issues/34
=> fix(layerswitcher)(dsfr): positionnement et rendu de la fenetre infos

samples-src/pages/tests/LayerSwitcher/pages-ol-layerswitcher-modules-addlayers.html, src/packages/Controls/LayerSwitcher/LayerSwitcher.js
#171 
Je m'abonne 
```js
layerSwitcher.on("layerswitcher:change:position", function (e) {
console.warn("layer", e, e.layer, e.position);
});
```
La nouvelle position de la couche est 0 (soit au dessus de la pile de couches)
=> fix(layerSwitcher): Ajout de l’événement de modification de position d'une couche

package.json, src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js, src/packages/Controls/Legends/LegendsDOM.js
Ajoute le libellé fermer aux panels du layerSwitcher et des Légendes
cf issue https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/334
=> fix(panels): ajoute libellé "fermer" aux panels à entete

package.json, src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
Tout est dans le titre : le mot zoomer est mal orthographié.
=> fix(ls): mauvaise orthographe pour le mot zoomer

package.json, src/packages/CSS/Controls/Territories/DSFRterritoriesStyle.css
Retrait d'une commande important dans la css territory qui empeche surcharge côté entrée carto
=> fix(terr:css): retrait important pour surcharge hauteur cote entree carto

package.json, src/packages/CSS/DSFRgeneralWidget.css, src/packages/Controls/Control.js
closes https://github.com/IGNF/geopf-extensions-openlayers/issues/200
Il reste quelques petites surcharges à faire côté entrée carto car la marge en haut pour les boutons n'est pas la même
=> feat(dsfr): dialog des widgets toujous en haut (a gauche ou a droite en fonction du positionnement du bouton)

package.json, src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
Retrait de l'import Config.
Utilisation d'une fonction getLayerTitle qui récupère par ordre de priorité : 
- le titre de la couche
- le name/id de la couche
- l'url de la couche
- un string vide
=> refacto(getFeatureInfo): récuperation du layer title sans utilisation de la configuration

package.json, src/packages/Controls/Catalog/Catalog.js, src/packages/Controls/Drawing/Drawing.js, src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js, src/packages/Controls/Isocurve/Isocurve.js, src/packages/Controls/LayerImport/LayerImport.js, src/packages/Controls/Legends/Legends.js, src/packages/Controls/MousePosition/MousePosition.js, src/packages/Controls/ReverseGeocode/ReverseGeocode.js, src/packages/Controls/Route/Route.js, src/packages/Controls/Territories/Territories.js, src/packages/Utils/Draggable.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/174
Refactor du draggable pour utiliser `transform: translate` à la place de top/bottom/left/right vu que ces 4 derniers sont utilisés pour le positionnement des dialog.
Ajout systématique de la map en tant que container en mode draggable pour les widgets.
=> feat(draggable): refactor

src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js
résolution du bug : 
fermeture du panel gfi qui ne se fait pas quand on ouvre un autre widget
=> fix gfi close panels with panel manager

package.json, src/packages/Controls/LayerImport/LayerImport.js, src/packages/Utils/PanelManager.js
Le bouton retour sur les panneaux de résultat est utile pour fermer le panneau sans supprimer les résultats. Ce qui est différent avec le bouton de fermeture, qui réinitialise le formulaire.
=> fix(LayerImport): Afficher le bouton retour sur la fenêtre des résultats

package.json, src/packages/Formats/Styling.js
Ex. de **GeoJSON** avec une _property_ `geom : null`
https://data.lillemetropole.fr/data/ogcapi/collections/gpu_habillage_lin/items?f=geojson&limit=-1
> On écarte les **features** dont la géométrie est inconnue ou nulle.
=> fix(LayerImport): Gestion des GeoJSON avec des géométries nulles

package.json, samples-src/pages/tests/Default/pages-ol-modules-dsrf-default.html, src/packages/CSS/DSFRgeneralWidget.css
fix #248 
Avant : 
le tooltip se place sous la barre d'echelle 
Après : 
le tooltip se place au dessus de la bar d'echelle
=> fix(scalebar): surcharge ol pour passer l'echelle sous les tooltips

package.json, src/packages/CSS/Controls/ElevationPath/DSFRelevationPathStyle.css
Fix #247 
Avant : 
la saisie d'un profil altimétrique dans la zone de la carte située sous la fenêtre de résultats du profil alti est ipossible
Après : 
la saisie dans la zone située sous la fenêtre de résultat d'un précédent calcul est possible
=> fix(alti-profile): #247 saisie ppossible sous la fenêtre de résultats

src/packages/CSS/DSFRgeneralWidget.css, src/packages/Controls/ReverseGeocode/ReverseGeocode.js, src/packages/Controls/Route/Route.js, src/packages/Controls/SearchEngine/SearchEngine.js, src/packages/Controls/Utils/Gfi.js
fix #244 
- coordonnées geographiques affichées
- pop-up compatible dark-mode
**RAF** (@azarz stp j'veux bien que tu le fasses, je reprendrai ton commit pour les prochaines fois) : 
Passer le bouton de fermeture de la pop-up compatible en dark-mode :
=> feat(search): info attributaires sur le marker de geolocalisation (#244)

package.json, src/packages/CSS/Controls/GetFeatureInfo/GPFgetFeatureInfo.css, src/packages/Controls/GetFeatureInfo/GetFeatureInfoDOM.js
Fix #253 
l'élément accordion dsfr impose une marge qui provoque une scrollbar horizontale. On surcharge le dsfr en inline css dans le code HTML de la pop-up (évite un !important).
Avant : 
Scrollbar horizontale inutile : 
Après : 
Plus de scrollbar :
=> fix(gfi): retrait d'une scrollbar horizontale inutile (#253)

DRAFT_CHANGELOG.md, build/webpack/layers.webpack.config.js, build/webpack/modules.webpack.config.js, package.json, samples-src/config.json, samples-src/pages/tests/Layers/pages-ol-layerwfs-modules-default.html, samples-src/pages/tests/Layers/pages-ol-layerwfs-modules-native.html, samples-src/pages/tests/Layers/pages-ol-sourcewfs-modules-default.html, samples-src/resources/data/configuration/sample.json, src/index.js, src/packages/Layers/LayerWFS.js, src/packages/Layers/SourceWFS.js, src/packages/bundle.js
Exemples 
```js
const vectorLayer = new ol.layer.GeoportalWFS({
layer: "BDTOPO_V3:batiment"
});
```
ou 
```js
const vectorLayer = new ol.layer.Vector({
source : new ol.source.GeoportalWFS({ layer : "BDTOPO_V3:batiment" })
});
```
Stratégie en place pour recupérer les features :
```text
Le moissonnage est actif
- sur un zoom min/max défini (par défaut, 15 à 21)
- sur l'étendu de la carte
Le nombre d’éléments à moissonner est défini par une valeur max : _maxFeatures_
On moissone tous les éléments de l'étendu par paquet de _maxFeatures_
Le déplacement sur la carte moissonne les données
Le style des données est défini par l'utilisateur (style par défaut d'openlayers) 
Le format d'export des données est en _GeoJSON_
```
:warning: Les performances !
=> feat(Layers): Ajout du format WFS

package.json, samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-default.html, samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-options.html, samples-src/pages/tests/Services/pages-ol-searchservice-modules-default.html, src/packages/CSS/Controls/SearchEngine/DSFRsearchEngineStyle.css, src/packages/Controls/Catalog/Catalog.js, src/packages/Controls/Catalog/CatalogDOM.js, src/packages/Controls/SearchEngine/SearchEngine.js, src/packages/Controls/SearchEngine/SearchEngineDOM.js, src/packages/Layers/SourceWFS.js, src/packages/Layers/SourceWMS.js, src/packages/Layers/SourceWMTS.js, src/packages/Services/Search.js
EDIT : fixes #269 (cf https://github.com/IGNF/geopf-extensions-openlayers/pull/267/commits/68bec559205a09587a7ef665ab1ad197dbf4997f)
- issue #254 
```js
// au niveau du service
Search.setFilterWMTSPriority(true);
// option sur SearchEngine
var search = new ol.control.SearchEngine({
searchOptions: {
filterWMTSPriority : true
}
});
```
avec ou sans option :
- Mise en avant de couches dans la recherche
> ces couches seront proposées avec un score plus élevé afin qu'elles apparaissent en 1ere position
```js
// au niveau du service 
const lstLayers = "PLAN.IGN,GEOGRAPHICALGRIDSYSTEMS.MAPS.BDUNI.J1,GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2,CADASTRALPARCELS.PARCELLAIRE_EXPRESS,ORTHOIMAGERY.ORTHOPHOTOS";
Search.setFiltersByLayerPriority(lstLayers);
// option sur SearchEngine
var search = new …
```
=> fix(Search): Amélioration de la recherche

package.json, samples-src/pages/tests/Default/pages-ol-modules-dsfr-default.html, src/packages/CSS/DSFRgeneralWidget.css, src/packages/Controls/LayerSwitcher/LayerSwitcher.js, src/packages/Controls/LayerSwitcher/LayerSwitcherDOM.js
fixes https://github.com/IGNF/geopf-extensions-openlayers/issues/276
fixe aussi l'affichage des btns tertiary qui ne sont pas directement les widgets
enlève des aria-pressed inutiles pouvant nuire à l'accessibilité
modifie l'appel au super() du Control LS pour uniformisation avec tous les controls héritant de ControlExtended
réajoute la classe gpf-widget-button au layerswitcher
=> fix(dsfr)(css): affichage des btns tertiary

DRAFT_CHANGELOG.md, package.json, src/packages/Controls/Drawing/Drawing.js, src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js, src/packages/Controls/Isocurve/Isocurve.js, src/packages/Controls/LayerSwitcher/LayerSwitcher.js, src/packages/Controls/Route/Route.js
Problème : 
- le GFI sur le Drawing renvoie comme nom de couche "undefined"
On ajoute donc le nom "Mon Croquis" par défaut à la VectorLayer, que l'on transmet au GFI.
cf.  https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/415
On en profite pour corriger le zoomToExtent du layerSwitcher sur les croquis
=> fix(drawing): Titre par défaut à la couche du croquis

samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-filter-duplicate.html, src/packages/Controls/SearchEngine/SearchEngine.js
Testable sur l'exemple : SearchEngine/pages-ol-searchengine-modules-dsfr-filter-duplicate.html
Le service d'autocompletion renvoie des résultats parfois insatisfaisants : 
- doublons dans le texte
- éléments dont on ne comprend pas le type
Quand on tape "Paris" dans la barre de recherche.
**Avant PR :** 
3 résultats : 
- la commune POI
- le département POI
- la municipalité street adresse
**Après PR (avec le bon paramétrage + il y a bien 5 resultats affichés, voir scrollbar) :** 
- on retire systématiquement les street adress ayant le type "municipality" (car semblent toujours dupliquées par une entrée à une commune POI)
- on ajoute le mot "département" au fullText des entrées poi de type "département". On fait de même pour les régions.
Quand on tape "Toulouse-le-château" dans la barre de …
=> feat(search) : Options pour améliorer l'affichage des résultats d'autocompletion

DRAFT_CHANGELOG.md, package.json, src/packages/CSS/Controls/Drawing/DSFRdrawingStyle.css, src/packages/Controls/SearchEngine/SearchEngine.js
Fixes https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/434
1 - le zoom sur sa geolocalisation est augmentée
2 - une croix de fermeture aux pop-ups affichées au clic sur les markers du searchEngine est ajoutée en mode DSFR
Attention : 
- partie pris de ne pas afficher "Fermer" en toutes lettres, car le résultat est un peu indigeste. Voir si c'est acceptable en terme d'accessibilité
=> Correction sur la pop-up affichée au clic des markers du searchEngine

DRAFT_CHANGELOG.md, package.json, samples-src/pages/tests/Measures/pages-ol-measures-modules-default.html, src/packages/Controls/Measures/MeasureLength.js
fix #293
**Si "m" :** 
```
var measureLength = new ol.control.MeasureLength({
unit : "m"
});
```
Les mesures de plus de 1000m s'affichent en m : 
**Si "km" :** 
```
var measureLength = new ol.control.MeasureLength({
unit : "km"
});
```
Les mesures de plus de 1000m s'affichent en m : 
**Si pas d'option unit spécifiée :** 
Le comportement actuel est conservé.
=> feat(measures): ajout option pour forcer unité d'affichage

package.json, src/packages/CSS/Controls/SearchEngine/DSFRsearchEngineStyle.css, src/packages/CSS/Controls/SearchEngine/GPFsearchEngine.css, src/packages/CSS/Controls/SearchEngine/GPFsearchEngineStyle.css, src/packages/CSS/GPFgeneralWidget.css, src/packages/Controls/SearchEngine/SearchEngineDOM.js
cf. https://github.com/IGNF/cartes.gouv.fr-entree-carto/issues/444
Conversion des `<select><options>` des résultats d'autocompletion, non affichés en mobile (normal), en `<div><p>`.
Pour tester : sur réseau perso, faire tourner les samples sur un PC. Se connecter en wifi avec le téléphone, et entrer l' https://<adresse_ip_du_pc>:<port_des_samples(8080)> dans la barre d'adresse de chrome.
Attention à bien tester en mode desktop.
=> fix(search): no autocomplete results on mobile

DRAFT_CHANGELOG.md, build/webpack/bundle.webpack.config.js, build/webpack/modules.webpack.config.js, package.json, src/packages/Controls/LayerImport/LayerImport.js, src/packages/Controls/LayerSwitcher/LayerSwitcher.js
cf. issue #235 et #51 
Pour le format **MapBox** importé, on peut utiliser le _zoom2Extent_ du **LayerSwitcher**.
Le calcul est réalisé via la grille des tuiles.
Pour tester, il suffit d'importer un fichier MapBox, le zoom sur l'étendu est realisé automatiquement.
Ensuite, on zoom et on se déplace sur la carte, et on procède à un zoom sur l'étendu dans le gestionnaire de couches.
=> fix(LayerSwitcher) : Zoom sur l'étendu du format MapBox importé

DRAFT_CHANGELOG.md, package.json, src/packages/CSS/Controls/LayerImport/DSFRlayerImportStyle.css, src/packages/CSS/Controls/LayerImport/GPFlayerImport.css, src/packages/CSS/Controls/LayerImport/GPFlayerImportStyle.css, src/packages/CSS/Controls/LocationSelector/DSFRlocationStyle.css, src/packages/CSS/Controls/LocationSelector/GPFlocation.css, src/packages/CSS/Controls/LocationSelector/GPFlocationStyle.css, src/packages/CSS/Controls/ReverseGeocoding/DSFRreverseGeocodingStyle.css, src/packages/CSS/Controls/SearchEngine/GPFsearchEngineStyle.css, src/packages/CSS/DSFRgeneralWidget.css, src/packages/Controls/LocationSelector/LocationSelectorDOM.js
fix #344 
fix #345 
Tester en mode classique et DSFR : 
- location selector partout où ils sont (route, isochrone..)
- import de couches (getCap WMS/WMTS + TMS)
La fenêtre des résultats n'est pas assez haute.
**AVANT**
**APRES**
**AVANT**
**APRES**
Augmentation de la largeur
Ajout d'une infobulle au survol long
Correction de la fenêtre transparente en mode classic
**AVANT**
**APRES**
**AVANT**
**APRES**
=> Fix(LocationSelector/LayerImport) : Corrections sur la taille des fenêtres de résultats d'imports et d'autocomplétion

DRAFT_CHANGELOG.md, package.json, samples-src/pages/tests/SearchEngine/pages-ol-searchengine-modules-dsfr-default.html, src/packages/Controls/SearchEngine/SearchEngine.js
Interfacage du filtre par projection.
Le paramètre filterProjection passé au SearchEngine permet d'ignorer les couches ayant l'une des projections listées.
EX. options pour que l'autocomplétion ne renvoie aucune couche en lambert 93.
```javascript
searchOptions: {
filterProjections: "IGNF:LAMB93"
}
},
```
Voir ligne commentée dans exemple searchengine dsfr
=> feat(searchEngine): ajout d'un filtre par projection des données

DRAFT_CHANGELOG.md, package.json, src/packages/Controls/GetFeatureInfo/GetFeatureInfo.js, src/packages/Controls/Utils/Gfi.js
AVANT : 
APRES : 
Fichier kml test : 
[test.txt](https://github.com/user-attachments/files/18827908/test.txt)
=> fix(gfi): retrait de propriétés liées aux labels dans la fenetre gfi

DRAFT_CHANGELOG.md, package.json, src/packages/Controls/Catalog/Catalog.js
Correction du catalogue (widget) : si une couche n'a pas de propriété serviceParams, on l'ignore, car non affichable.
Le problème se pose si une couche de la configuration du widget n'est pas chargée dans la configuration des couches de la carte.
C'est l'équivalent côté entrée carto de la vérification que tous les id dans edito.json sont bien dans layers.json
=> fix(Catalog): vérification qu'on a bien la propriété serviceParams

DRAFT_CHANGELOG.md, package.json, samples-src/pages/tests/Catalog/pages-ol-catalog-modules-dsfr-type-data-without-config.html, samples-src/resources/data/configuration/sample.json, samples-src/templates/partials/packages/partials-ol-bundle-dsfr-head.hbs, samples-src/templates/partials/packages/partials-ol-bundle-head.hbs, samples-src/templates/partials/packages/partials-ol-modules-dsfr-head.hbs, samples-src/templates/partials/packages/partials-ol-modules-head.hbs, src/packages/Controls/Catalog/Catalog.js, src/packages/Controls/Catalog/CatalogDOM.js, src/packages/Controls/Catalog/sample.json, src/packages/Controls/LayerSwitcher/LayerSwitcher.js, src/packages/Layers/SourceWFS.js, src/packages/Utils/LayerConfigUtils.js, src/packages/Utils/TMS.json
3 évolutions 
* Méthode publique pour ajouter à la volée des couches dans le widget.
Ex. ajout de 2 config de couches WFS
```js
catalog.addLayerConfig({
"BDTOPO_V3:departement$GEOPORTAIL:OGC:WFS" : {
"name": "BDTOPO_V3:departement",
"title": "BDTOPO : Départements",
"description": "Départements − BDTOPO",
"globalConstraint": {
"minScaleDenominator": 0,
"maxScaleDenominator": 62236752975597,
"bbox": {
"left": -63.28125,
"right": 55.8984375,
"top": 51.9734375,
"bottom": -21.77265625
}
},
"serviceParams": {
"id": "OGC:WFS",
"version": "2.0.0",
"serverUrl": {
"full": "https://data.geopf.fr/wfs/wfs"
}
},
"defaultProjection": "EPSG:4326",
"queryable": false,
"metadata": [],
"styles": [],
"legends": [],
"formats": []
},
"BDTOPO_V3:commune$GEOPORTAIL:OGC:WFS" : {
"name": "BDTOPO_V3:commune", …
```
=> feat(catalog): Méthode publique pour intégrer à la volée une conf dans le composant

DRAFT_CHANGELOG.md, package.json, samples-src/pages/tests/Drawing/pages-ol-drawing-modules-dsfr-edition.html, src/packages/Controls/Drawing/Drawing.js
cf. issue #379 
```js
var drawing = new ol.control.Drawing({
position: "top-left",
layerDescription : {
title: "Croquis par défaut", // par défaut, Croquis
description : "C'est mon croquis" // par défaut, Mon croquis
}
});
```
=> fix(drawing): Prise en compte de l'option layerDescription

DRAFT_CHANGELOG.md, package.json, samples-src/pages/tests/Drawing/pages-ol-drawing-modules-dsfr-forget-listen.html, src/packages/Controls/Drawing/Drawing.js, src/packages/Controls/LayerSwitcher/LayerSwitcher.js
Ajout des méthodes publiques **forget** et **listen** pour (des)activer l'écouteur d'ajout de couches.
Ceci permet de cacher l'affichage d'une couche sur le gestionnaire de couches.
Ex.
```js
// on desactive l'écouteur du layerswitcher avant que le croquis soit ajouté à la carte
drawing.on("drawing:add:before", function(e) {
console.log("before drawing add", e);
layerSwitcher.forget();
e.layer.setZIndex(1000); // Hack pour avoir les croquis toujours au dessus
});
// on reactive l'écouteur du layerswitcher aprés que la couche croquis soit ajoutée à la carte 
drawing.on("drawing:add:after", function(e) {
console.log("after drawing add", e);
layerSwitcher.listen();
});
```
Recetter avec l'exemple : `samples-src/pages/tests/Drawing/pages-ol-drawing-modules-dsfr-forget-listen.html`
=> feat(layerswitcher) : Ajout méthodes forget & listen sur l'écouteur d'ajout de couche

DRAFT_CHANGELOG.md, package.json, src/packages/Controls/ContextMenu/ContextMenu.js
Voir #350 pour la correction de la requête WFS Limites administratives sur la table commune.
Pour l'elevation, lon et lat étaient inversés : -99999 toujours renvoyé. 
Etrange : en prod entrée carto pas de problème ?!
=> fix(ContextMenu) : correction de la requete WFS pour récupérer la commune et de l'altimétrie
